In [1]:
import pandas as pd

df = pd.read_csv('/content/Loan_Default.csv')

display(df.head())
display(df.info())

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758.0,CIB,25-34,to_inst,98.728814,south,direct,1.0,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552.0,EXP,55-64,to_inst,NaN,North,direct,1.0,NaN
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834.0,CIB,35-44,to_inst,80.019685,south,direct,0.0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587.0,CIB,45-54,not_inst,69.376900,North,direct,0.0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602.0,EXP,25-34,not_inst,91.886544,North,direct,0.0,39.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76810 entries, 0 to 76809
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         76810 non-null  int64
 1   year                       76810 non-null  int64
 2   loan_limit                 75091 non-null  object
 3   Gender                     76810 non-null  object
 4   approv_in_adv              76365 non-null  object
 5   loan_type                  76810 non-null  object
 6   loan_purpose               76743 non-null  object
 7   Credit_Worthiness          76810 non-null  object
 8   open_credit                76810 non-null  object
 9   business_or_commercial     76810 non-null  object
 10  loan_amount                76810 non-null  int64
 11  rate_of_interest           57957 non-null  float64
 12  Interest_rate_spread       57858 non-null  float64
 13  Upfront_charges            56287 non-null  float64
 14  term                       76784 non-null  float64
 15  Neg_ammortization          76753 non-null  object
 16  interest_only              76809 non-null  object
 17  lump_sum_payment           76809 non-null  object
 18  property_value             69059 non-null  float64
 19  construction_type          76809 non-null  object
 20  occupancy_type             76809 non-null  object
 21  Secured_by                 76809 non-null  object
 22  total_units                76809 non-null  object
 23  income                     72153 non-null  float64
 24  credit_type                76809 non-null  object
 25  Credit_Score               76809 non-null  float64
 26  co-applicant_credit_type   76809 non-null  object
 27  age                        76710 non-null  object
 28  submission_of_application  76710 non-null  object
 29  LTV                        69059 non-null  float64
 30  Region                     76809 non-null  object
 31  Security_Type              76809 non-null  object
 32  Status                     76809 non-null  float64
 33  dtir1                      64463 non-null  float64
dtypes: float64(10), int64(3), object(21)
memory usage: 19.9+ MB

None

In [2]:
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]

numeric_cols_with_missing = df[missing_values.index].select_dtypes(include=['float64', 'int64']).columns
categorical_cols_with_missing = df[missing_values.index].select_dtypes(include=['object']).columns

for col in numeric_cols_with_missing:
    df[col].fillna(df[col].median(), inplace=True)

for col in categorical_cols_with_missing:
    df[col].fillna(df[col].mode()[0], inplace=True)

display(df.isnull().sum().sum())

/tmp/ipython-input-2238722.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipython-input-2238722.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

np.int64(0)

In [3]:
import numpy as np

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[col] = df[col].apply(lambda x: upper_bound if x > upper_bound else (lower_bound if x < lower_bound else x))

display(df.describe())

,ID,year,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,property_value,income,Credit_Score,LTV,Status,dtir1
count,76810.000000,76810.0,76810.000000,76810.000000,76810.000000,76810.000000,76810.0,7.681000e+04,76810.000000,76810.000000,76810.000000,76810.0,76810.000000
mean,63294.500000,2019.0,328003.450072,4.023445,0.419608,2879.339856,360.0,4.670521e+05,6442.715011,699.789624,73.143948,0.0,38.159074
std,22173.281425,0.0,168934.780428,0.451817,0.410133,2207.788580,0.0,2.425038e+05,3531.621131,115.843150,17.116390,0.0,9.132946
min,24890.000000,2019.0,26500.000000,3.000000,-0.470562,0.000000,360.0,8.000000e+03,0.000000,500.000000,31.198489,0.0,16.500000
25%,44092.250000,2019.0,196500.000000,3.750000,0.180400,1250.000000,360.0,2.880000e+05,3840.000000,599.000000,63.392857,0.0,33.000000
50%,63294.500000,2019.0,296500.000000,3.990000,0.388200,2594.620000,360.0,4.180000e+05,5700.000000,699.000000,75.201613,0.0,39.000000
75%,82496.750000,2019.0,436500.000000,4.250000,0.614375,3900.000000,360.0,5.980000e+05,8280.000000,800.000000,84.855769,0.0,44.000000
max,101699.000000,2019.0,796500.000000,5.000000,1.265337,7875.000000,360.0,1.063000e+06,14940.000000,900.000000,117.050137,0.0,60.500000

In [4]:
categorical_cols = df.select_dtypes(include='object').columns

threshold = 0.05

for col in categorical_cols:
    value_counts = df[col].value_counts(normalize=True)
    infrequent_categories = value_counts[value_counts < threshold].index
    df[col] = df[col].replace(infrequent_categories, 'Other')
    print(f"Value counts for {col} after grouping infrequent categories:")
    display(df[col].value_counts())

Value counts for loan_limit after grouping infrequent categories:

loan_limit
cf     71614
ncf     5196
Name: count, dtype: int64

Value counts for Gender after grouping infrequent categories:

Gender
Male                 21879
Joint                21334
Sex Not Available    19441
Female               14156
Name: count, dtype: int64

Value counts for approv_in_adv after grouping infrequent categories:

approv_in_adv
nopre    64905
pre      11905
Name: count, dtype: int64

Value counts for loan_type after grouping infrequent categories:

loan_type
type1    58447
type2    10681
type3     7682
Name: count, dtype: int64

Value counts for loan_purpose after grouping infrequent categories:

loan_purpose
p3       29050
p4       28224
p1       17866
Other     1670
Name: count, dtype: int64

Value counts for Credit_Worthiness after grouping infrequent categories:

Credit_Worthiness
l1       73560
Other     3250
Name: count, dtype: int64

Value counts for open_credit after grouping infrequent categories:

open_credit
nopc     76540
Other      270
Name: count, dtype: int64

Value counts for business_or_commercial after grouping infrequent categories:

business_or_commercial
nob/c    66129
b/c      10681
Name: count, dtype: int64

Value counts for Neg_ammortization after grouping infrequent categories:

Neg_ammortization
not_neg    68916
neg_amm     7894
Name: count, dtype: int64

Value counts for interest_only after grouping infrequent categories:

interest_only
not_int    73237
Other       3573
Name: count, dtype: int64

Value counts for lump_sum_payment after grouping infrequent categories:

lump_sum_payment
not_lpsm    75094
Other        1716
Name: count, dtype: int64

Value counts for construction_type after grouping infrequent categories:

construction_type
sb       76796
Other       14
Name: count, dtype: int64

Value counts for occupancy_type after grouping infrequent categories:

occupancy_type
pr       71475
Other     5335
Name: count, dtype: int64

Value counts for Secured_by after grouping infrequent categories:

Secured_by
home     76796
Other       14
Name: count, dtype: int64

Value counts for total_units after grouping infrequent categories:

total_units
1U       75700
Other     1110
Name: count, dtype: int64

Value counts for credit_type after grouping infrequent categories:

credit_type
CIB     24949
CRIF    22572
EXP     21439
EQUI     7850
Name: count, dtype: int64

Value counts for co-applicant_credit_type after grouping infrequent categories:

co-applicant_credit_type
CIB    38611
EXP    38199
Name: count, dtype: int64

Value counts for age after grouping infrequent categories:

age
45-54    18120
35-44    17048
55-64    16700
65-74    10592
25-34     9962
Other     4388
Name: count, dtype: int64

Value counts for submission_of_application after grouping infrequent categories:

submission_of_application
to_inst     49581
not_inst    27229
Name: count, dtype: int64

Value counts for Region after grouping infrequent categories:

Region
North      38662
south      32990
central     4511
Other        647
Name: count, dtype: int64

Value counts for Security_Type after grouping infrequent categories:

Security_Type
direct    76796
Other        14
Name: count, dtype: int64

In [5]:
categorical_cols = df.select_dtypes(include='object').columns

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

display(df.head())
display(df.info())

,ID,year,loan_amount,rate_of_interest,Interest_rate_spread,Upfront_charges,term,property_value,income,Credit_Score,...,age_35-44,age_45-54,age_55-64,age_65-74,age_Other,submission_of_application_to_inst,Region_Other,Region_central,Region_south,Security_Type_direct
0,24890,2019,116500.0,3.99,0.3882,2594.62,360.0,118000.0,1740.0,758.0,...,False,False,False,False,False,True,False,False,True,True
1,24891,2019,206500.0,3.99,0.3882,2594.62,360.0,418000.0,4980.0,552.0,...,False,False,True,False,False,True,False,False,False,True
2,24892,2019,406500.0,4.56,0.2000,595.00,360.0,508000.0,9480.0,834.0,...,True,False,False,False,False,True,False,False,True,True
3,24893,2019,456500.0,4.25,0.6810,2594.62,360.0,658000.0,11880.0,587.0,...,False,True,False,False,False,False,False,False,False,True
4,24894,2019,696500.0,4.00,0.3042,0.00,360.0,758000.0,10440.0,602.0,...,False,False,False,False,False,False,False,False,False,True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76810 entries, 0 to 76809
Data columns (total 47 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 76810 non-null  int64
 1   year                               76810 non-null  int64
 2   loan_amount                        76810 non-null  float64
 3   rate_of_interest                   76810 non-null  float64
 4   Interest_rate_spread               76810 non-null  float64
 5   Upfront_charges                    76810 non-null  float64
 6   term                               76810 non-null  float64
 7   property_value                     76810 non-null  float64
 8   income                             76810 non-null  float64
 9   Credit_Score                       76810 non-null  float64
 10  LTV                                76810 non-null  float64
 11  Status                             76810 non-null  float64
 12  dtir1                              76810 non-null  float64
 13  loan_limit_ncf                     76810 non-null  bool
 14  Gender_Joint                       76810 non-null  bool
 15  Gender_Male                        76810 non-null  bool
 16  Gender_Sex Not Available           76810 non-null  bool
 17  approv_in_adv_pre                  76810 non-null  bool
 18  loan_type_type2                    76810 non-null  bool
 19  loan_type_type3                    76810 non-null  bool
 20  loan_purpose_p1                    76810 non-null  bool
 21  loan_purpose_p3                    76810 non-null  bool
 22  loan_purpose_p4                    76810 non-null  bool
 23  Credit_Worthiness_l1               76810 non-null  bool
 24  open_credit_nopc                   76810 non-null  bool
 25  business_or_commercial_nob/c       76810 non-null  bool
 26  Neg_ammortization_not_neg          76810 non-null  bool
 27  interest_only_not_int              76810 non-null  bool
 28  lump_sum_payment_not_lpsm          76810 non-null  bool
 29  construction_type_sb               76810 non-null  bool
 30  occupancy_type_pr                  76810 non-null  bool
 31  Secured_by_home                    76810 non-null  bool
 32  total_units_Other                  76810 non-null  bool
 33  credit_type_CRIF                   76810 non-null  bool
 34  credit_type_EQUI                   76810 non-null  bool
 35  credit_type_EXP                    76810 non-null  bool
 36  co-applicant_credit_type_EXP       76810 non-null  bool
 37  age_35-44                          76810 non-null  bool
 38  age_45-54                          76810 non-null  bool
 39  age_55-64                          76810 non-null  bool
 40  age_65-74                          76810 non-null  bool
 41  age_Other                          76810 non-null  bool
 42  submission_of_application_to_inst  76810 non-null  bool
 43  Region_Other                       76810 non-null  bool
 44  Region_central                     76810 non-null  bool
 45  Region_south                       76810 non-null  bool
 46  Security_Type_direct               76810 non-null  bool
dtypes: bool(34), float64(11), int64(2)
memory usage: 10.1 MB

None

In [20]:
from sklearn.preprocessing import MinMaxScaler

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
if 'ID' in numeric_cols:
    numeric_cols.remove('ID')
if 'Status' in numeric_cols:
    numeric_cols.remove('Status')

scaler = MinMaxScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

display(df.head())

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,rate_of_interest_binned,Interest_rate_spread_binned,Upfront_charges_binned,property_value_binned,income_binned,LTV_binned,dtir1_binned,loan_to_income,Credit_Score_poly_0,Credit_Score_poly_1
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,0.428571,0.428571,0.333333,0.000000,0.000000,1.000000,0.777778,0.0,0.6450,0.416025
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,0.428571,0.428571,0.333333,0.444444,0.333333,0.444444,0.444444,0.0,0.1300,0.016900
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,0.857143,0.285714,0.000000,0.666667,0.888889,0.666667,0.888889,0.0,0.8350,0.697225
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,0.714286,0.714286,0.333333,0.777778,0.888889,0.333333,0.666667,0.0,0.2175,0.047306
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,0.571429,0.428571,0.000000,0.888889,0.888889,0.888889,0.444444,0.0,0.2550,0.065025

In [23]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

if 'rate_of_interest' in df.columns and 'Interest_rate_spread' in df.columns:
    df['interest_rate_x_spread'] = df['rate_of_interest'] * df['Interest_rate_spread']
else:
    print("Warning: 'rate_of_interest' or 'Interest_rate_spread' column not found. 'interest_rate_x_spread' not created.")

if 'loan_amount' in df.columns and 'income' in df.columns and (df['income'] != 0).any():
    df['loan_to_income'] = df['loan_amount'] / df['income']
    max_loan_to_income = df['loan_to_income'][np.isfinite(df['loan_to_income'])].max()
    if np.isinf(max_loan_to_income):
         df['loan_to_income'].replace([np.inf, -np.inf], 0, inplace=True)
        df['loan_to_income'].replace([np.inf, -np.inf], max_loan_to_income, inplace=True)

    df['loan_to_income'].fillna(df['loan_to_income'].median(), inplace=True)
else:
    df['loan_to_income'] = 0
    print("Warning: 'loan_amount' or 'income' column not found or 'income' contains only zero values. 'loan_to_income' created with placeholder values.")


if 'Credit_Score' in df.columns:
    poly = PolynomialFeatures(degree=2, include_bias=False)
    credit_score_poly = poly.fit_transform(df[['Credit_Score']])
    poly_feature_names = [f'Credit_Score_poly_{i}' for i in range(credit_score_poly.shape[1])]
    credit_score_poly_df = pd.DataFrame(credit_score_poly, columns=poly_feature_names, index=df.index)
    df = pd.concat([df, credit_score_poly_df], axis=1)
else:
    print("Warning: 'Credit_Score' column not found. Polynomial feature for 'Credit_Score' not created.")


display(df.head())

Warning: 'rate_of_interest' or 'Interest_rate_spread' column not found. 'interest_rate_x_spread' not created.
Warning: 'loan_amount' or 'income' column not found or 'income' contains only zero values. 'loan_to_income' created with placeholder values.

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,Upfront_charges_binned,property_value_binned,income_binned,LTV_binned,dtir1_binned,loan_to_income,Credit_Score_poly_0,Credit_Score_poly_1,Credit_Score_poly_0,Credit_Score_poly_1
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,0.333333,0.000000,0.000000,1.000000,0.777778,0,0.6450,0.416025,0.6450,0.416025
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,0.333333,0.444444,0.333333,0.444444,0.444444,0,0.1300,0.016900,0.1300,0.016900
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,0.000000,0.666667,0.888889,0.666667,0.888889,0,0.8350,0.697225,0.8350,0.697225
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,0.333333,0.777778,0.888889,0.333333,0.666667,0,0.2175,0.047306,0.2175,0.047306
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,0.000000,0.888889,0.888889,0.888889,0.444444,0,0.2550,0.065025,0.2550,0.065025

In [22]:
continuous_cols = ['loan_amount', 'rate_of_interest', 'Interest_rate_spread', 'Upfront_charges', 'property_value', 'income', 'LTV', 'dtir1']

for col in continuous_cols:
    if col in df.columns:
        df[f'{col}_binned'] = pd.qcut(df[col], q=10, labels=False, duplicates='drop')
        df = df.drop(columns=[col])
    else:
        print(f"Column '{col}' not found in the DataFrame.")


display(df.head())
if 'loan_amount_binned' in df.columns:
    display(df['loan_amount_binned'].value_counts().sort_index())
elif 'rate_of_interest_binned' in df.columns:
     display(df['rate_of_interest_binned'].value_counts().sort_index())

Column 'loan_amount' not found in the DataFrame.
Column 'rate_of_interest' not found in the DataFrame.
Column 'Interest_rate_spread' not found in the DataFrame.
Column 'Upfront_charges' not found in the DataFrame.
Column 'property_value' not found in the DataFrame.
Column 'income' not found in the DataFrame.
Column 'LTV' not found in the DataFrame.
Column 'dtir1' not found in the DataFrame.

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,rate_of_interest_binned,Interest_rate_spread_binned,Upfront_charges_binned,property_value_binned,income_binned,LTV_binned,dtir1_binned,loan_to_income,Credit_Score_poly_0,Credit_Score_poly_1
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,0.428571,0.428571,0.333333,0.000000,0.000000,1.000000,0.777778,0.0,0.6450,0.416025
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,0.428571,0.428571,0.333333,0.444444,0.333333,0.444444,0.444444,0.0,0.1300,0.016900
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,0.857143,0.285714,0.000000,0.666667,0.888889,0.666667,0.888889,0.0,0.8350,0.697225
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,0.714286,0.714286,0.333333,0.777778,0.888889,0.333333,0.666667,0.0,0.2175,0.047306
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,0.571429,0.428571,0.000000,0.888889,0.888889,0.888889,0.444444,0.0,0.2550,0.065025

loan_amount_binned
0.000000    7969
0.111111    8452
0.222222    7617
0.333333    7877
0.444444    6891
0.555556    7883
0.666667    8067
0.777778    7613
0.888889    7250
1.000000    7191
Name: count, dtype: int64

In [21]:
continuous_cols = ['loan_amount', 'rate_of_interest', 'Interest_rate_spread', 'Upfront_charges', 'property_value', 'income', 'LTV', 'dtir1']

for col in continuous_cols:
    if col in df.columns:
        df[f'{col}_binned'] = pd.qcut(df[col], q=10, labels=False, duplicates='drop')
        df = df.drop(columns=[col])
    else:
        print(f"Column '{col}' not found in the DataFrame.")


display(df.head())
if 'loan_amount_binned' in df.columns:
    display(df['loan_amount_binned'].value_counts().sort_index())
elif 'rate_of_interest_binned' in df.columns:
     display(df['rate_of_interest_binned'].value_counts().sort_index())

Column 'loan_amount' not found in the DataFrame.
Column 'rate_of_interest' not found in the DataFrame.
Column 'Interest_rate_spread' not found in the DataFrame.
Column 'Upfront_charges' not found in the DataFrame.
Column 'property_value' not found in the DataFrame.
Column 'income' not found in the DataFrame.
Column 'LTV' not found in the DataFrame.
Column 'dtir1' not found in the DataFrame.

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,rate_of_interest_binned,Interest_rate_spread_binned,Upfront_charges_binned,property_value_binned,income_binned,LTV_binned,dtir1_binned,loan_to_income,Credit_Score_poly_0,Credit_Score_poly_1
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,0.428571,0.428571,0.333333,0.000000,0.000000,1.000000,0.777778,0.0,0.6450,0.416025
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,0.428571,0.428571,0.333333,0.444444,0.333333,0.444444,0.444444,0.0,0.1300,0.016900
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,0.857143,0.285714,0.000000,0.666667,0.888889,0.666667,0.888889,0.0,0.8350,0.697225
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,0.714286,0.714286,0.333333,0.777778,0.888889,0.333333,0.666667,0.0,0.2175,0.047306
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,0.571429,0.428571,0.000000,0.888889,0.888889,0.888889,0.444444,0.0,0.2550,0.065025

loan_amount_binned
0.000000    7969
0.111111    8452
0.222222    7617
0.333333    7877
0.444444    6891
0.555556    7883
0.666667    8067
0.777778    7613
0.888889    7250
1.000000    7191
Name: count, dtype: int64

In [7]:
import numpy as np
from scipy.stats import skew, boxcox

numeric_cols = df.select_dtypes(include=np.number).columns

skewness = df[numeric_cols].apply(lambda x: skew(x.dropna()))
skewed_cols = skewness[abs(skewness) > 0.5].index

for col in skewed_cols:
    if (df[col] > 0).all():
        if abs(skewness[col]) > 1:
             df[col], _ = boxcox(df[col])
        else:
            df[col] = np.log1p(df[col])
    else:
        df[col] = np.sqrt(df[col] + abs(df[col].min()))

transformed_skewness = df[skewed_cols].apply(lambda x: skew(x.dropna()))

print("Original Skewness:")
display(skewness[skewed_cols])
print("\nTransformed Skewness:")
display(transformed_skewness)

Original Skewness:

loan_amount        0.683664
Upfront_charges    0.731122
property_value     0.847658
income             0.846171
LTV               -0.572061
dtype: float64

Transformed Skewness:

loan_amount        0.072490
Upfront_charges   -0.495738
property_value     0.269430
income             0.006459
LTV               -1.740261
dtype: float64

In [14]:
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

target_variable = 'Status'

print("Original dataset shape %s" % Counter(df[target_variable]))

X = df.drop(target_variable, axis=1)
y = df[target_variable]

if len(y.unique()) > 1:
    smote = SMOTE(random_state=42)
    X_res, y_res = smote.fit_resample(X, y)
    print('Resampled dataset shape %s' % Counter(y_res))
else:
    print("The target variable has only one class. SMOTE cannot be applied.")

Original dataset shape Counter({0.0: 76810})
The target variable has only one class. SMOTE cannot be applied.

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (61448, 49)
Shape of X_test: (15362, 49)
Shape of y_train: (61448,)
Shape of y_test: (15362,)

In [19]:
continuous_cols = ['loan_amount', 'rate_of_interest', 'Interest_rate_spread', 'Upfront_charges', 'property_value', 'income', 'LTV', 'dtir1']

for col in continuous_cols:
    if col in df.columns:
        df[f'{col}_binned'] = pd.qcut(df[col], q=10, labels=False, duplicates='drop')
        df = df.drop(columns=[col])
    else:
        print(f"Column '{col}' not found in the DataFrame.")


display(df.head())
if 'loan_amount_binned' in df.columns:
    display(df['loan_amount_binned'].value_counts().sort_index())
elif 'rate_of_interest_binned' in df.columns:
     display(df['rate_of_interest_binned'].value_counts().sort_index())

Column 'loan_amount' not found in the DataFrame.
Column 'rate_of_interest' not found in the DataFrame.
Column 'Interest_rate_spread' not found in the DataFrame.
Column 'Upfront_charges' not found in the DataFrame.
Column 'property_value' not found in the DataFrame.
Column 'income' not found in the DataFrame.
Column 'LTV' not found in the DataFrame.
Column 'dtir1' not found in the DataFrame.

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,rate_of_interest_binned,Interest_rate_spread_binned,Upfront_charges_binned,property_value_binned,income_binned,LTV_binned,dtir1_binned,loan_to_income,Credit_Score_poly_0,Credit_Score_poly_1
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,0.428571,0.428571,0.333333,0.000000,0.000000,1.000000,0.777778,0.0,0.6450,0.416025
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,0.428571,0.428571,0.333333,0.444444,0.333333,0.444444,0.444444,0.0,0.1300,0.016900
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,0.857143,0.285714,0.000000,0.666667,0.888889,0.666667,0.888889,0.0,0.8350,0.697225
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,0.714286,0.714286,0.333333,0.777778,0.888889,0.333333,0.666667,0.0,0.2175,0.047306
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,0.571429,0.428571,0.000000,0.888889,0.888889,0.888889,0.444444,0.0,0.2550,0.065025

loan_amount_binned
0.000000    7969
0.111111    8452
0.222222    7617
0.333333    7877
0.444444    6891
0.555556    7883
0.666667    8067
0.777778    7613
0.888889    7250
1.000000    7191
Name: count, dtype: int64

In [9]:
continuous_cols = ['loan_amount', 'rate_of_interest', 'Interest_rate_spread', 'Upfront_charges', 'property_value', 'income', 'LTV', 'dtir1']

for col in continuous_cols:
    if col in df.columns:
        df[f'{col}_binned'] = pd.qcut(df[col], q=10, labels=False, duplicates='drop')
        df = df.drop(columns=[col])
    else:
        print(f"Column '{col}' not found in the DataFrame.")


display(df.head())
if 'loan_amount_binned' in df.columns:
    display(df['loan_amount_binned'].value_counts().sort_index())
elif 'rate_of_interest_binned' in df.columns:
     display(df['rate_of_interest_binned'].value_counts().sort_index())

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,Region_south,Security_Type_direct,loan_amount_binned,rate_of_interest_binned,Interest_rate_spread_binned,Upfront_charges_binned,property_value_binned,income_binned,LTV_binned,dtir1_binned
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,True,True,0,3,3,2,0,0,9,7
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,False,True,2,3,3,2,4,3,4,4
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,True,True,6,6,2,0,6,8,6,8
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,False,True,7,5,5,2,7,8,3,6
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,False,True,9,4,3,0,8,8,8,4

loan_amount_binned
0    7969
1    8452
2    7617
3    7877
4    6891
5    7883
6    8067
7    7613
8    7250
9    7191
Name: count, dtype: int64

In [24]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

if 'rate_of_interest' in df.columns and 'Interest_rate_spread' in df.columns:
    df['interest_rate_x_spread'] = df['rate_of_interest'] * df['Interest_rate_spread']
else:
    print("Warning: 'rate_of_interest' or 'Interest_rate_spread' column not found. 'interest_rate_x_spread' not created.")

if 'loan_amount' in df.columns and 'income' in df.columns and (df['income'] != 0).any():
    df['loan_to_income'] = df['loan_amount'] / df['income']
    max_loan_to_income = df['loan_to_income'][np.isfinite(df['loan_to_income'])].max()
    if np.isinf(max_loan_to_income):
         df['loan_to_income'].replace([np.inf, -np.inf], 0, inplace=True)
    else:
        df['loan_to_income'].replace([np.inf, -np.inf], max_loan_to_income, inplace=True)

    df['loan_to_income'].fillna(df['loan_to_income'].median(), inplace=True)
else:
    df['loan_to_income'] = 0
    print("Warning: 'loan_amount' or 'income' column not found or 'income' contains only zero values. 'loan_to_income' created with placeholder values.")


if 'Credit_Score' in df.columns:
    poly = PolynomialFeatures(degree=2, include_bias=False)
    credit_score_poly = poly.fit_transform(df[['Credit_Score']])
    poly_feature_names = [f'Credit_Score_poly_{i}' for i in range(credit_score_poly.shape[1])]
    credit_score_poly_df = pd.DataFrame(credit_score_poly, columns=poly_feature_names, index=df.index)
    df = pd.concat([df, credit_score_poly_df], axis=1)
else:
    print("Warning: 'Credit_Score' column not found. Polynomial feature for 'Credit_Score' not created.")


display(df.head())

Warning: 'rate_of_interest' or 'Interest_rate_spread' column not found. 'interest_rate_x_spread' not created.
Warning: 'loan_amount' or 'income' column not found or 'income' contains only zero values. 'loan_to_income' created with placeholder values.

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,income_binned,LTV_binned,dtir1_binned,loan_to_income,Credit_Score_poly_0,Credit_Score_poly_1,Credit_Score_poly_0,Credit_Score_poly_1,Credit_Score_poly_0,Credit_Score_poly_1
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,0.000000,1.000000,0.777778,0,0.6450,0.416025,0.6450,0.416025,0.6450,0.416025
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,0.333333,0.444444,0.444444,0,0.1300,0.016900,0.1300,0.016900,0.1300,0.016900
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,0.888889,0.666667,0.888889,0,0.8350,0.697225,0.8350,0.697225,0.8350,0.697225
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,0.888889,0.333333,0.666667,0,0.2175,0.047306,0.2175,0.047306,0.2175,0.047306
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,0.888889,0.888889,0.444444,0,0.2550,0.065025,0.2550,0.065025,0.2550,0.065025

In [25]:
target_variable = 'Status'
X = df.drop(target_variable, axis=1)
y = df[target_variable]

variances = X.var()

variance_threshold = 0.01
low_variance_features = variances[variances < variance_threshold].index

X_new = X.drop(columns=low_variance_features)

print("Original X shape:", X.shape)
print("New X shape after dropping low-variance features:", X_new.shape)

X = X_new

Original X shape: (76810, 53)
New X shape after dropping low-variance features: (76810, 45)

In [32]:
print("Number of features after feature selection:", X.shape[1])

if X.shape[1] > 30:
    from sklearn.decomposition import PCA

    pca = PCA(n_components=0.95, random_state=42)

    X_pca = pca.fit_transform(X)

    print("Shape of X after PCA:", X_pca.shape)

else:
    print("Number of features is not excessively large, PCA may not be necessary.")

Number of features after feature selection: 53
Shape of X after PCA: (76810, 28)

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (61448, 28)
Shape of X_test: (15362, 28)
Shape of y_train: (61448,)
Shape of y_test: (15362,)

In [37]:

zero_percentage = (X == 0).sum().sum() / (X.shape[0] * X.shape[1])

print(f"Percentage of zero values in the feature matrix: {zero_percentage:.2f}%")

print("\nFeature integration is complete. The 'X' variable contains the processed features.")
display(pd.DataFrame(X).head()) # Display as DataFrame for better readability

Percentage of zero values in the feature matrix: 0.00%

Feature integration is complete. The 'X' variable contains the processed features.

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,0.380201,0.906069,0.019708,0.566767,1.055877,-0.183181,-0.692969,-0.444946,-0.340647,0.013007,...,-0.067584,-0.493711,-0.111032,-0.093789,0.055157,0.170320,-0.057403,-0.036758,0.020586,0.295587
1,-0.909520,0.283163,0.586867,-0.696876,0.986821,-0.140886,0.386322,-0.303425,-0.132769,0.679014,...,-0.228669,-0.485110,-0.359007,-0.192818,-0.153548,0.061617,0.070302,0.047590,-0.180323,-0.092108
2,0.902769,0.012797,0.814083,0.473290,0.643564,0.077283,-1.310109,-0.410370,0.227263,-0.237717,...,-0.841715,-0.513129,0.497538,-0.401146,-0.216797,0.116138,-0.347041,0.126102,-0.036684,0.097245
3,-0.814282,-0.647290,0.960869,0.658409,-0.507702,-0.665859,-0.318438,0.688988,-0.427121,0.204241,...,0.105590,-0.483542,-0.357855,0.121785,0.002522,0.107794,-0.044381,-0.095233,0.026659,-0.105207
4,-0.777043,-1.212015,-0.073111,-0.781807,0.400248,1.035616,-0.318872,-0.162800,-0.192265,0.273545,...,-0.016435,-0.508955,-0.212811,-0.041840,0.215533,0.152651,-0.331166,-0.044108,-0.092287,0.083823

In [36]:
print("Number of features after feature selection:", X.shape[1])

if X.shape[1] > 30:
    from sklearn.decomposition import PCA

    pca = PCA(n_components=0.95, random_state=42)

    X_pca = pca.fit_transform(X)

    X = X_pca

    print("Shape of X after PCA:", X.shape)

else:
    print("Number of features is not excessively large, PCA may not be necessary.")

Number of features after feature selection: 53
Shape of X after PCA: (76810, 28)

In [11]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

if 'rate_of_interest' in df.columns and 'Interest_rate_spread' in df.columns:
    df['interest_rate_x_spread'] = df['rate_of_interest'] * df['Interest_rate_spread']
else:
    print("Warning: 'rate_of_interest' or 'Interest_rate_spread' column not found. 'interest_rate_x_spread' not created.")

if 'loan_amount' in df.columns and 'income' in df.columns and (df['income'] != 0).any():
    df['loan_to_income'] = df['loan_amount'] / df['income']
    max_loan_to_income = df['loan_to_income'][np.isfinite(df['loan_to_income'])].max()
    if np.isinf(max_loan_to_income):
         df['loan_to_income'].replace([np.inf, -np.inf], 0, inplace=True)
    else:
        df['loan_to_income'].replace([np.inf, -np.inf], max_loan_to_income, inplace=True)

    df['loan_to_income'].fillna(df['loan_to_income'].median(), inplace=True)
else:
    df['loan_to_income'] = 0
    print("Warning: 'loan_amount' or 'income' column not found or 'income' contains only zero values. 'loan_to_income' created with placeholder values.")


if 'Credit_Score' in df.columns:
    poly = PolynomialFeatures(degree=2, include_bias=False)
    credit_score_poly = poly.fit_transform(df[['Credit_Score']])
    poly_feature_names = [f'Credit_Score_poly_{i}' for i in range(credit_score_poly.shape[1])]
    credit_score_poly_df = pd.DataFrame(credit_score_poly, columns=poly_feature_names, index=df.index)
    df = pd.concat([df, credit_score_poly_df], axis=1)
else:
    print("Warning: 'Credit_Score' column not found. Polynomial feature for 'Credit_Score' not created.")


display(df.head())

Warning: 'rate_of_interest' or 'Interest_rate_spread' column not found. 'interest_rate_x_spread' not created.
Warning: 'loan_amount' or 'income' column not found or 'income' contains only zero values. 'loan_to_income' created with placeholder values.

,ID,year,term,Credit_Score,Status,loan_limit_ncf,Gender_Joint,Gender_Male,Gender_Sex Not Available,approv_in_adv_pre,...,rate_of_interest_binned,Interest_rate_spread_binned,Upfront_charges_binned,property_value_binned,income_binned,LTV_binned,dtir1_binned,loan_to_income,Credit_Score_poly_0,Credit_Score_poly_1
0,0.000000,0.0,0.0,0.6450,0.0,False,False,False,True,False,...,3,3,2,0,0,9,7,0,0.6450,0.416025
1,0.000013,0.0,0.0,0.1300,0.0,False,False,True,False,False,...,3,3,2,4,3,4,4,0,0.1300,0.016900
2,0.000026,0.0,0.0,0.8350,0.0,False,False,True,False,True,...,6,2,0,6,8,6,8,0,0.8350,0.697225
3,0.000039,0.0,0.0,0.2175,0.0,False,False,True,False,False,...,5,5,2,7,8,3,6,0,0.2175,0.047306
4,0.000052,0.0,0.0,0.2550,0.0,False,True,False,False,True,...,4,3,0,8,8,8,4,0,0.2550,0.065025

In [12]:
target_variable = 'Status'
X = df.drop(target_variable, axis=1)
y = df[target_variable]

variances = X.var()

variance_threshold = 0.01
low_variance_features = variances[variances < variance_threshold].index

X_new = X.drop(columns=low_variance_features)

print("Original X shape:", X.shape)
print("New X shape after dropping low-variance features:", X_new.shape)

X = X_new

Original X shape: (76810, 49)
New X shape after dropping low-variance features: (76810, 41)

In [13]:
print("Number of features after feature selection:", X.shape[1])

if X.shape[1] > 30:
    from sklearn.decomposition import PCA

    pca = PCA(n_components=0.95, random_state=42)

    X_pca = pca.fit_transform(X)

    X = X_pca

    print("Shape of X after PCA:", X.shape)

else:
    print("Number of features is not excessively large, PCA may not be necessary.")

Number of features after feature selection: 41
Number of features is still large, considering PCA.
Shape of X after PCA: (76810, 11)